#!/bin/bash
#
# Run full testing to the Autoship.
#

set -e

ci_script=`dirname "${BASH_SOURCE[0]}"`
export WORKDIR=`realpath "$ci_script"`

run() {
  ln -sf $WORKDIR/../ci $WORKDIR
  rm -fr $WORKDIR/.autoship
  set -x
  cd $WORKDIR

  AUTOANSWER=default ./ci > /dev/null
  [[ -f .autoship/config ]]
  [[ -f .autoship/repos/local/config ]]
  ./ci help > /dev/null
  ./ci help repo > /dev/null
  ./ci info > /dev/null
  ./ci repo add git@github.com:wigy/ci-autoship.git > /dev/null 2>&1
  ./ci repo ls > /dev/null
  ./ci rebuild-docker > /dev/null
  REPO=ci-autoship AUTOANSWER=default ./ci node-lint > /dev/null
  AUTOANSWER=default ./ci node-unit > /dev/null
  AUTOANSWER=default ./ci node-lint > /dev/null
  AUTOANSWER=default ./ci node-build > /dev/null
  AUTOANSWER=default ./ci apidoc-build > /dev/null

  set +x
  echo
  echo -e "\e[32mSUCCESS\e[0m"
  echo
}

echo "Testing...."
run
