#!/bin/bash
#
# Print text in color.
#
#   color-print [-n] <color>|<purpose> <text>...
#

set -e

if [[ "$1" == -n ]]; then
  N="-e $1"
  shift
else
  N='-e'
fi

case "$1" in
  green|info)
    shift
    echo $N "\e[32m$*\e[0m"
    ;;
  orange|prompt)
    shift
    echo $N "\e[33m$*\e[0m"
    ;;
  yellow|question|code)
    shift
    echo $N "\e[0;93m$*\e[0m"
    ;;
  blue|heading)
    shift
    echo $N "\e[34m$*\e[0m"
    ;;
  magenta|title|debug)
    shift
    echo $N "\e[35m$*\e[0m"
    ;;
  cyan)
    shift
    echo $N "\e[36m$*\e[0m"
    ;;
  red|error)
    shift
    echo $N "\e[31m$*\e[0m"
    ;;
  white|text)
    shift
    echo $N "\e[37m$*\e[0m"
    ;;
  note)
    shift
    echo $N "\e[0;92m$*\e[0m"
    ;;
  *)
    error-exit INVALID_ARGS "Bad color '$1'."
    ;;
esac
