#!/bin/bash
#
# Define REPO and BRANCH variables if not defined based on environment.
#
#   repo-select [<variable-prefix>]
#

set -e

# Direct environment.
if [[ ! -z "$REPO" ]]; then
  if [[ -z "$BRANCH" ]]; then
    export BRANCH=master
    export TARGET="$WORKDIR"/.autoship/repos/$REPO/branches/master
  fi
else
  if [[ -z "`repo-list`" ]]; then
    error-exit NOT_FOUND "There are not any repositories."
  fi
  if [[ ! `repo-list` =~ ' ' ]]; then
    export REPO=`repo-list`
    export BRANCH=master
    export TARGET="$WORKDIR"/.autoship/repos/$REPO/branches/master
  else
    if grep -q "$1" "$WORKDIR/.autoship/repos"/*/config; then
      repo=`grep -l "$1" "$WORKDIR/.autoship/repos"/*/config | head -n 1`
      repo=`dirname "$repo"`
      export REPO=`basename "$repo"`
      export BRANCH=master
      export TARGET="$WORKDIR"/.autoship/repos/$REPO/branches/master
    else
      error-exit NOT_FOUND "Cannot find a repository and/or branch for working (maybe define env REPO and BRANCH)."
    fi
  fi
fi

# Check existence.
if ! repo-exists $REPO; then
  error-exit NOT_FOUND "There is no repo '$REPO' checked out."
fi
if ! repo-exists $REPO $BRANCH; then
  error-exit NOT_FOUND "There is no branch '$BRANCH' of '$REPO' checked out."
fi
