#!/bin/bash
#
# Fetch and print variable value from the repository configuration.
#
#   repo-conf-get <repo> <name> [<default>]
#

set -e

if grep -q "^$2" "$WORKDIR/.autoship/repos/$1/config"; then
  grep "^$2=" < "$WORKDIR/.autoship/repos/$1/config" | sed -e "s/^$2=//"
else
  echo "$3"
fi
