#!/bin/bash

set -e

#
# Resolve package manager. Requires $REPO setting.
#
node_package_manager() {
  local pm
  NODE_PACKAGE_MANAGER=`repo-conf-get "$REPO" NODE_PACKAGE_MANAGER`
  if [[ -z "$NODE_PACKAGE_MANAGER" ]]; then
    if pnpm --version > /dev/null 2>&1; then
      pm=pnpm
    else
      if yarn --version > /dev/null 2>&1; then
        pm=yarn
      else
        pm npm
      fi
    fi

    NODE_PACKAGE_MANAGER=`question-str "What is your Node package manager" "$pm"`
    repo-conf-set $REPO NODE_PACKAGE_MANAGER "$NODE_PACKAGE_MANAGER"
  fi

  export NODE_PACKAGE_MANAGER
}

#
# Find a dir variable from repo config. Help to find it if not yet set.
#
node_resolve_dir() {
  local name=$1
  local msg=$2
  local value

  value=`repo-conf-get "$REPO" $name`
  if [[ -z "$value" ]]; then
    package_json=`find "$WORKDIR" -name 'package.json' | head -n 1`
    if [[ -z "$package_json" ]]; then
      error-exit NOT_FOUND "Unable to find any directory with package.json file."
    fi
    local_path=`dirname ${package_json/"$TARGET/"}`
    value=`question-dir "$msg (type '.' for root dir)" "$local_path"`

    repo-conf-set $REPO $name "$value"
  fi

  export $name="$value"
}
